"""Add 2fa columns

Revision ID: 3149207c61ad
Revises: 
Create Date: 2023-12-09 22:29:16.674305

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3149207c61ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_two_factor_authentication_enabled', sa.Boolean(), nullable=False, default=False))
        batch_op.add_column(sa.Column('secret_token', sa.String(), nullable=True))
        batch_op.create_unique_constraint("secret_token_unique_key", ['secret_token'])
        batch_op.create_unique_constraint("email_token_unique_key", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("secret_token_unique_key", type_='unique')
        batch_op.drop_constraint("email_token_unique_key", type_='unique')
        batch_op.drop_column('secret_token')
        batch_op.drop_column('is_two_factor_authentication_enabled')

    # ### end Alembic commands ###
